version: '3'
volumes:
  datavolume: {}
services:
  redis:
    container_name: nova-scaffold-dex-redis
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    logging: &logging_default
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '200m'
        compress: 'true'
  ethereum-node:
    container_name: nova-scaffold-dex-ethereum-node
    image: novaprotocolio/ethereum-test-node:latest
    ports:
      - 8545:8545
    restart: always
    logging:
      <<: *logging_default
  db:
    container_name: nova-scaffold-dex-pg
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - datavolume:/var/lib/postgresql/data
      - ../backend/db/migrations/0001-init.up.sql:/docker-entrypoint-initdb.d/0001-init.up.sql
      - ./envs/localhost/seed.sql:/docker-entrypoint-initdb.d/0002-seed.sql
    logging:
      <<: *logging_default
  web:
    build: ./web
    container_name: nova-scaffold-dex-web
    ports:
      - 3000:8043
    environment:
      - CONFIG_VARS=REACT_APP_API_URL,REACT_APP_WS_URL,REACT_APP_NODE_URL,REACT_APP_NOVA_PROXY_ADDRESS,REACT_APP_NOVA_TOKEN_ADDRESS,REACT_APP_WETH_TOKEN_ADDRESS,REACT_APP_NETWORK_ID
      - REACT_APP_API_URL=http://api:3001
      - REACT_APP_WS_URL=ws://ws:3002
      - REACT_APP_NODE_URL=http://ethereum-node:8545
      - REACT_APP_NOVA_PROXY_ADDRESS=0x1D52a52f5996FDff37317a34EBFbeC7345Be3b55
      - REACT_APP_NOVA_TOKEN_ADDRESS=0x224E34A640FC4108FABDb201eD85D909059105fA
      - REACT_APP_WETH_TOKEN_ADDRESS=0x7Cb242e4f8EE3FE4F1f244209c05B794F192353E
      - REACT_APP_NETWORK_ID=66
    restart: always
    logging:
      <<: *logging_default
  admin:
    build: ./backend
    container_name: nova-scaffold-dex-admin-api
    command: /bin/adminapi
    ports:
      - 3003:3003
    environment:
      - NSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - NSK_REDIS_URL=redis://redis:6379/0
      - NSK_BLOCKCHAIN_RPC_URL=http://ethereum-node:8545
      - NSK_LOG_LEVEL=ERROR
      - WEB_HEALTH_CHECK_URL=http://web:8043
      - API_HEALTH_CHECK_URL=http://api:4001/metrics
      - ENGINE_HEALTH_CHECK_URL=http://engine:4004/metrics
      - LAUNCHER_HEALTH_CHECK_URL=http://launcher:4005/metrics
      - WATCHER_HEALTH_CHECK_URL=http://watcher:4003/metrics
      - WEBSOCKET_HEALTH_CHECK_URL=http://ws:4002/metrics
      - NSK_PROXY_ADDRESS=0x1D52a52f5996FDff37317a34EBFbeC7345Be3b55
      - NSK_RELAYER_ADDRESS=0x93388b4efe13b9b18ed480783c05462409851547
    volumes:
      - datavolume:/data
    depends_on:
      - db
      - redis
      - ethereum-node
    restart: always
    logging:
      <<: *logging_default
  api:
    build: ./backend
    container_name: nova-scaffold-dex-api
    command: /bin/api
    ports:
      - 3001:3001
      - 4001:4001
    environment:
      - NSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - NSK_REDIS_URL=redis://redis:6379/0
      - NSK_HYBRID_EXCHANGE_ADDRESS=0x7aCf426255a3DEbe19f664341De77e361e1F79db
      - NSK_BLOCKCHAIN_RPC_URL=http://ethereum-node:8545
      - NSK_NOVA_TOKEN_ADDRESS=0x224E34A640FC4108FABDb201eD85D909059105fA
      - NSK_PROXY_ADDRESS=0x1D52a52f5996FDff37317a34EBFbeC7345Be3b55
      - NSK_RELAYER_ADDRESS=0x93388b4efe13b9b18ed480783c05462409851547
      - NSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4001
    volumes:
      - datavolume:/data
    depends_on:
      - db
      - redis
      - ethereum-node
    restart: always
    logging:
      <<: *logging_default
  ws:
    build: ./backend
    container_name: nova-scaffold-dex-ws
    command: /bin/websocket
    ports:
      - 3002:3002
      - 4002:4002
    environment:
      - NSK_API_URL=http://api:3001
      - NSK_REDIS_URL=redis://redis:6379/0
      - NSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4002
    volumes:
      - datavolume:/data
    depends_on:
      - redis
      - api
    restart: always
    logging:
      <<: *logging_default
  watcher:
    build: ./backend
    container_name: nova-scaffold-dex-watcher
    command: /bin/watcher
    ports:
      - 4003:4003
    environment:
      - NSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - NSK_REDIS_URL=redis://redis:6379/0
      - NSK_BLOCKCHAIN_RPC_URL=http://ethereum-node:8545
      - NSK_LOG_LEVEL=DEBUG
      - NSK_HYBRID_EXCHANGE_ADDRESS=0x7aCf426255a3DEbe19f664341De77e361e1F79db
      - METRICS_PORT=4003
    volumes:
      - datavolume:/data
    depends_on:
      - redis
      - ethereum-node
      - db
    restart: always
    logging:
      <<: *logging_default
  engine:
    build: ./backend
    container_name: nova-scaffold-dex-engine
    command: /bin/engine
    environment:
      - NSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - NSK_REDIS_URL=redis://redis:6379/0
      - NSK_HYBRID_EXCHANGE_ADDRESS=0x7aCf426255a3DEbe19f664341De77e361e1F79db
      - NSK_PROXY_ADDRESS=0x1D52a52f5996FDff37317a34EBFbeC7345Be3b55
      - NSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4004
    volumes:
      - datavolume:/data
    depends_on:
      - redis
      - db
    restart: always
    logging:
      <<: *logging_default
  launcher:
    build: ./backend
    container_name: nova-scaffold-dex-launcher
    command: /bin/launcher
    environment:
      - NSK_DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - NSK_BLOCKCHAIN_RPC_URL=http://ethereum-node:8545
      - NSK_HYBRID_EXCHANGE_ADDRESS=0x7aCf426255a3DEbe19f664341De77e361e1F79db
      - NSK_RELAYER_ADDRESS=0x93388b4efe13b9b18ed480783c05462409851547
      - NSK_RELAYER_PK=95b0a982c0dfc5ab70bf915dcf9f4b790544d25bc5e6cff0f38a59d0bba58651
      - NSK_LOG_LEVEL=DEBUG
      - METRICS_PORT=4005
    volumes:
      - datavolume:/data
    depends_on:
      - ethereum-node
      - db
    restart: always
    logging:
      <<: *logging_default
  maker:
    image: novaprotocolio/amm-bots
    container_name: nova-scaffold-dex-maker
    depends_on:
      - api
    environment:
      - BOT_TYPE=CONST_PRODUCT
      - BOT_PRIVATE_KEY=0xa6553a3cbade744d6c6f63e557345402abd93e25cd1f1dba8bb0d374de2fcf4f
      - BOT_BASE_TOKEN=HOT
      - BOT_QUOTE_TOKEN=DAI
      - BOT_BASE_URL=http://api:3001
      - BOT_MIN_PRICE=0.8
      - BOT_MAX_PRICE=1.2
      - BOT_PRICE_GAP=0.02
      - BOT_EXPAND_INVENTORY=2
      - BOT_WEB3_URL=http://ethereum-node:8545
    restart: on-failure:10
    logging:
      <<: *logging_default
